services:
  documents-rag:
    container_name: documents-rag
    build: .
    env_file:
      - .env
    volumes:
      - .:/app
    command: bash
    stdin_open: true
    tty: true

  documents-rag-qdrant:
    container_name: documents-rag-qdrant
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333" # HTTP
      - "6334:6334" # gRPC
    volumes:
      - qdrant_data:/qdrant/storage
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__GRPC_PORT=6334

volumes:
  qdrant_data:
